const bedsTowns = [
    'Ampthill',
    'Arlesey',
    'Barton-le-Clay',
    'Bedford',
    'Biggleswade',
    'Caddington',
    'Cople',
    'Cranfield',
    'Dunstable',
    'Eaton Bray',
    'Flitwick',
    'Harlington',
    'Houghton Regis',
    'Husborne Crawley',
    'Kempston',
    'Leighton Buzzard',
    'Lidlington',
    'Linslade',
    'Luton',
    'Milton Keynes',
    'Potton',
    'Pulloxhill',
    'Sandy',
    'Shefford',
    'Stotfold',
    'Toddington',
    'Turvey',
    'Willington',
    'Woburn',
    'Wootton',
  ];
  

export default bedsTowns; 
