const essexTowns = [
    'Alresford',
    'Asheldham',
    'Barking',
    'Barling',
    'Basildon',
    'Billericay',
    'Bobbingworth',
    'Borley',
    'Bradwell-on-Sea',
    'Braintree',
    'Brentwood',
    'Brightlingsea',
    'Buckhurst Hill',
    'Burnham-on-Crouch',
    'Canvey Island',
    'Chappel',
    'Chelmsford',
    'Chigwell',
    'Chipping Ongar',
    'Clacton-on-Sea',
    'Clacton',
    'Coggeshall',
    'Colchester',
    'Crays Hill',
    'Dagenham',
    'Danbury',
    'Earls Colne',
    'Epping',
    'Felsted',
    'Frinton-on-Sea',
    'Grays',
    'Great Dunmow',
    'Hadleigh',
    'Halstead',
    'Harlow',
    'Harwich',
    'Hockley',
    'Hornchurch',
    'Ilford',
    'Ingatestone',
    'Kelvedon Hatch',
    'Lamarsh',
    'Langham',
    'Leigh-on-Sea',
    'Loughton',
    'Maldon',
    'Manningtree',
    'Marks Tey',
    'Nazeing',
    'Newport',
    'North Weald Bassett',
    'Pilgrims Hatch',
    'Pitsea',
    'Purfleet',
    'Rainham',
    'Rayleigh',
    'Rochford',
    'Romford',
    'Saffron Walden',
    'Shenfield',
    'Shoeburyness',
    'Sible Hedingham',
    'South Benfleet',
    'South Woodham Ferrers',
    'Southend-on-Sea',
    'Southminster',
    'Stanford Le Hope',
    'Stansted Mountfitchet',
    'Thaxted',
    'Thorpe le Soken',
    'Thundersley',
    'Tilbury',
    'Tiptree',
    'Tollesbury',
    'Waltham Abbey',
    'Walton-on-the-Naze',
    'West Mersea',
    'Westcliff-on-Sea',
    'Wethersfield',
    'White Roding',
    'Wickford',
    'Widdington',
    'Witham',
    'Wivenhoe',
    'Woodford Green',
    'Writtle'
];

export default essexTowns;
