const fs = require('fs');
const path = require('path');

const outputFolder = './';

// Array of towns
const towns = [
'Abbots Langley',
'Adeyfield',
'Albury',
'Albury End',
'Aldbury',
'Aldenham',
'Aley Green',
'Amwell',
'Ansells End',
'Anstey',
'Apsley',
'Ardeley',
'Ashwell',
'Ashwell End',
'Aspenden',
'Aston',
'Aston End',
'Ayot Green',
'Ayot St Lawrence',
'Ayot St Peter',
'Ayres End',
'Babbs Green',
'Bakers End',
'Baldock',
'Barkway',
'Barley',
'Barleycroft End',
'Barwick',
'Bassus Green',
'Batchworth',
'Batchworth Heath',
'Batford',
'Batlers Green',
'Bayford',
'Beane',
'Bedmond',
'Bedwell',
'Bell Bar',
'Belsize',
'Bendish',
'Bengeo',
'Benington',
'Bennetts End',
'Bentley Heath',
'Berkhamsted',
'Bernards Heath',
'Birch Green',
'Birchwood',
'Bishop\'s Stortford',
'Blackmore End',
'Blue Hill',
'Borehamwood',
'Bourne End',
'Bovingdon',
'Bovingdon Green',
'Bower Heath',
'Boxmoor',
'Bozen Green',
'Bragbury End',
'Bramfield',
'Braughing',
'Braughing Friars',
'Breachwood Green',
'Brent Pelham',
'Brickendon',
'Bricket Wood',
'Broad Colney',
'Broadgreen Wood',
'Broadoak End',
'Broadwater',
'Broken Green',
'Bromley',
'Brook End',
'Brookmans Park',
'Broxbourne',
'Buckland',
'Bucks Hill',
'Bulbourne',
'Bulstrode',
'Buntingford',
'Burge End',
'Burnham Green',
'Bury Green',
'Bushey',
'Bushey Heath',
'Bygrave',
'Cadwell',
'Caldecote',
'Caldecote Hill',
'Cam (Rhee)',
'Carpenders Park',
'Chapel Green',
'Chapmore End',
'Charlton',
'Chaulden',
'Cheapside',
'Chells',
'Cherry Green',
'Cheshunt',
'Childwick Bury',
'Childwick Green',
'Chiltern Hills',
'Chipperfield',
'Chipping',
'Chiswell Green',
'Chorleywood',
'Chorleywood Bottom',
'Church End',
'Churchgate',
'Clapgate',
'Clay End',
'Clothall',
'Clothall Common',
'Codicote',
'Codicote Bottom',
'Cokenach',
'Cold Christmas',
'Cold Harbour',
'Cole Green',
'Coleman Green',
'Colliers End',
'Colne',
'Colney Heath',
'Colney Street',
'Commonwood',
'Cottered',
'Counters End',
'Cow Roast',
'Crabbs Green',
'Cradle End',
'Cromer',
'Cromer-Hyde',
'Croxley Green',
'Cuffley',
'Cumberlow Green',
'Cupid Green',
'Damask Green',
'Dancers Hill',
'Dane End',
'Danesbury',
'Darleyhall',
'Dassels',
'Datchworth',
'Datchworth Green',
'Deacons Hill',
'Dewes Green',
'Digswell',
'Digswell Park',
'Digswell Water',
'Dudswell',
'East End',
'East End Green',
'Easthall',
'Ellenbrook',
'Elstree',
'Epping Green',
'Essendon',
'Farnham Green',
'Fields End',
'Fishers Green',
'Flamstead',
'Flamstead End',
'Flaunden',
'Fleetville',
'Ford End',
'Frithsden',
'Frogmore',
'Furneux Pelham',
'Gade',
'Gadebridge',
'Ganwick Corner',
'Garston',
'Gaston Green',
'Gilston',
'Gilston Park',
'Goose Green',
'Gorhambury',
'Gosmore',
'Grand Union Canal',
'Graveley',
'Gravesend',
'Great Amwell',
'Great Gaddesden',
'Great Hormead',
'Great Munden',
'Great Offley',
'Great Wymondley',
'Green End',
'Green Street',
'Green Tye',
'Grove, The',
'Grovehill',
'Gubblecote',
'Guilden Morden',
'Gustard Wood',
'Hadham Cross',
'Hadham Ford',
'Hailey',
'Haldens',
'Hall Grove',
'Hammerfield',
'Hammond Street',
'Handside',
'Hare Street',
'Harmer Green',
'Harpenden',
'Harpenden Common',
'Hartham',
'Hatching Green',
'Hatfield',
'Hatfield Garden Village',
'Hatfield Hyde',
'Haultwick',
'Hay Green',
'Hay Street',
'Hebing End',
'Helham Green',
'Hemel Hempstead',
'Heronsgate',
'Hertford',
'Hertford Heath',
'Hertingfordbury',
'Hexton',
'High Cross',
'Broadgreen Wood',
'Broadoak End',
'Broadwater',
'Broken Green',
'Bromley',
'Brook End',
'Brookmans Park',
'Broxbourne',
'Buckland',
'Bucks Hill',
'Bulbourne',
'Bulstrode',
'Buntingford',
'Burge End',
'Burnham Green',
'Bury Green',
'Bushey',
'Bushey Heath',
'Bygrave',
'Cadwell',
'Caldecote',
'Caldecote Hill',
'Cam (Rhee)',
'Carpenders Park',
'Chapel Green',
'Chapmore End',
'Charlton',
'Chaulden',
'Cheapside',
'Chells',
'Cherry Green',
'Cheshunt',
'Childwick Bury',
'Childwick Green',
'Chiltern Hills',
'Chipperfield',
'Chipping',
'Chiswell Green',
'Chorleywood',
'Chorleywood Bottom',
'Church End',
'Churchgate',
'Clapgate',
'Clay End',
'Clothall',
'Clothall Common',
'Codicote',
'Codicote Bottom',
'Cokenach',
'Cold Christmas',
'Cold Harbour',
'Cole Green',
'Coleman Green',
'Colliers End',
'Colne',
'Colney Heath',
'Colney Street',
'Commonwood',
'Cottered',
'Counters End',
'Cow Roast',
'Crabbs Green',
'Cradle End',
'Cromer',
'Cromer-Hyde',
'Croxley Green',
'Cuffley',
'Cumberlow Green',
'Cupid Green',
'Damask Green',
'Dancers Hill',
'Dane End',
'Danesbury',
'Darleyhall',
'Dassels',
'Datchworth',
'Datchworth Green',
'Deacons Hill',
'Dewes Green',
'Digswell',
'Digswell Park',
'Digswell Water',
'Dudswell',
'East End',
'East End Green',
'Easthall',
'Ellenbrook',
'Elstree',
'Epping Green',
'Essendon',
'Farnham Green',
'Fields End',
'Fishers Green',
'Flamstead',
'Flamstead End',
'Flaunden',
'Fleetville',
'Ford End',
'Frithsden',
'Frogmore',
'Furneux Pelham',
'Gade',
'Gadebridge',
'Ganwick Corner',
'Garston',
'Gaston Green',
'Gilston',
'Gilston Park',
'Goose Green',
'Gorhambury',
'Gosmore',
'Grand Union Canal',
'Graveley',
'Gravesend',
'Great Amwell',
'Great Gaddesden',
'Great Hormead',
'Great Munden',
'Great Offley',
'Great Wymondley',
'Green End',
'Green Street',
'Green Tye',
'Grove, The',
'Grovehill',
'Gubblecote',
'Guilden Morden',
'Long Marston',
'Loudwater',
'Lower Green',
'Lower Woodside',
'Lucas End',
'Luffenhall',
'Mackerye End',
'Maple Cross',
'Mardleybury',
'Markyate',
'Marshalls Heath',
'Marshalswick',
'Marshmoor',
'Meesden',
'Meriden',
'Merry Hill',
'Micklefield Green',
'Mill End',
'Mill Green',
'Mimram',
'Moneyhill',
'Moor Green',
'Moor Park',
'Much Hadham',
'Nash Mills',
'Nast Hyde',
'Nasty',
'Nether Street',
'Nettleden',
'New Greens',
'New Ground',
'New Mill',
'New River',
'Newgate Street',
'Newnham',
'Newsells',
'Nobland Green',
'Nomansland',
'North Watford',
'Northaw',
'Northchurch',
'Norton',
'Norton Green',
'Nup End',
'Nuthampstead',
'Oakfield',
'Oaklands',
'Old Hall Green',
'Old Hatfield',
'Old Knebworth',
'Old Town',
'Oughton',
'Oxhey',
'Oxlease',
'Panshanger',
'Park Street',
'Patchetts Green',
'Patient End',
'Patmore Heath',
'Peartree',
'Perry Green',
'Peters Green',
'Piccotts End',
'Pimlico',
'Pin Green',
'Pirton',
'Pitstone',
'Poplars',
'Potten End',
'Potters Bar',
'Potters Crouch',
'Pottersheath',
'Pouchen End',
'Presdales',
'Preston',
'Puckeridge',
'Purwell',
'Rableyheath',
'Radlett',
'Radwell',
'Redbourn',
'Redbournbury',
'Redhill',
'Reed',
'Reed End',
'Rhee (Cam)',
'Rib',
'Rickmansworth',
'Ridge',
'Roe End',
'Roe Green',
'Roestock',
'Rosedale',
'Round Bush',
'Rowley Green',
'Royston',
'Rucklers Lane',
'Rush Green',
'Rushden',
'Rusling End',
'Rye Park',
'Sacombe',
'Sacombe Green',
'Sandon',
'Sandridge',
'Sarratt',
'Sawbridgeworth',
'Shaftenhoe End',
'Shaw Green',
'Shenley',
'Shenleybury',
'Shephall',
'Sherrardspark',
'Shootersway',
'Sleapshyde',
'Slip End',
'Smallford',
'Smug Oak',
'Snailswell',
'Snow End',
'Sopwell',
'South Hatfield',
'South Mimms',
'South Oxhey',
'South-end',
'Southern Green',
'Spellbrook',
'Spitalbrook',
'St Albans',
'St Ibbs',
'St Ippollitts',
'St Julians',
'St Margarets',
'St Nicholas',
'St Stephens',
'Staines Green',
'Stanborough',
'Standon',
'Standon Green End',
'Stanstead Abbots',
'Stapleford',
'Stevenage',
'Stocking Pelham',
'Stort',
'Swanley Bar',
'Symonds Green',
'Tea Green',
'Tewin',
'Tewin Wood',
'The Camp',
'The Folly',
'The Frythe',
'The Grove',
'The Node',
'The Ridgeway',
'The Rookery',
'The Ryde',
'The Swillett',
'Therfield',
'Thorley',
'Thorley Houses',
'Thorley Street',
'Throcking',
'Thundridge',
'Titmore Green',
'Tolmers',
'Tonwell',
'Tower Hill',
'Townsend',
'Trims Green',
'Tring',
'Tring Wharf',
'Tringford',
'Trowley Bottom',
'Turnford',
'Two Waters',
'Tylers Causeway',
'Tyttenhanger',
'Uppend',
'Upper Dunsley',
'Upwick Green',
'Venus Hill',
'Ver',
'Wadesmill',
'Wakeley',
'Walkern',
'Wallington',
'Walnuttree Green',
'Walsworth',
'Ware',
'Wareside',
'Warners End',
'Washall Green',
'Water End',
'Waterdale',
'Waterend',
'Waterford',
'Watford',
'Watford Heath',
'Watton at Stone',
'Welham Green',
'Well End',
'Wellpond Green',
'Welwyn',
'Welwyn Garden City',
'West End',
'West Hyde',
'West Watford',
'Westbrook Hay',
'Westland Green',
'Westmill',
'Weston',
'Westwick Row',
'Wheathampstead',
'Whempstead',
'Whippendell Botton',
'White Hall',
'Whitehall',
'Whitwell',
'Widford',
'Wigginton',
'Wigginton Bottom',
'Wildhill',
'Willian',
'Wilstone',
'Wilstone Reservoir',
'Wood End',
'Woodhall',
'Woodside',
'Woollensbrook',
'Woolmer Green',
'Wormley',
'Wormley West End',
'Wormleybury',
'Wyddial',
'Wymondley Bury',
'Youngsbury'
];

// Template path
const templatePath = path.join(__dirname, 'FenceInstallers.astro');

// Read the template content
let templateContent = fs.readFileSync(templatePath, 'utf8');

// Create the output directory if it doesn't exist
if (!fs.existsSync(outputFolder)) {
  fs.mkdirSync(outputFolder, { recursive: true });
}

// Generate pages for each town
towns.forEach((town) => {
  // Replace {town} in the template content with the actual town name
  const pageContent = templateContent.replace(/{town}/g, town);

  // Convert town for URL (lowercase with hyphen)
  const urlTown = town.toLowerCase().replace(/\s+/g, '-');

  // Define the output path
  const outputPath = path.join(outputFolder, `${urlTown}.astro`);

  // Write the modified content to the output file
  fs.writeFileSync(outputPath, pageContent, 'utf8');
  console.log(`Generated page for ${town} at ${outputPath}`);
});

console.log('Pages generated successfully.');
